Repository AY2425S1-CS2103T-T10-4/tp, pull requests merged in 2024-11, with the labels that each got.

#165 Enhance event equality check
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/exceptions/DuplicateEventException.java
Labels: type.Enhancement, type.Bug, priority.High

#169 Updated UG
  docs/UserGuide.md
  docs/images/findBennyWilliamsonResult.png
Labels: UG

#170 Update command bug fixes
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/logic/parser/UpdateCommandParser.java
  src/test/java/seedu/address/logic/commands/EventCommandTest.java
Labels: priority.High, severity.High

#240 Revert event equality changes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/UpdateCommand.java
  src/main/java/seedu/address/model/event/Event.java
Labels: priority.High, severity.High, Backend

#244 Update UG for truncation in the person detailed card
  docs/UserGuide.md
Labels: UG
