Repository AY2425S1-CS2103T-T10-4/tp, pull requests merged in 2024-10, with the labels that each got.

#10 Add Gilbert's photo
  docs/images/gilbb.jpg
Labels: type.Task, priority.High

#18 Update AboutUs for Gilbert
  docs/AboutUs.md
  docs/images/gilbb.png
  docs/team/gilbb.md
Labels: type.Task, priority.High

#31 fix issue templates
  ISSUE_TEMPLATE/bug_report.md
  ISSUE_TEMPLATE/issue_template.md
Labels: type.Task

#59 Cancel feature
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/CancelCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CancelCommandParser.java
Labels: type.Story, Backend

#103 Event enhancement: adding support for attendees
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EventCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EventCommandTest.java
  src/test/java/seedu/address/testutil/EventBuilder.java
Labels: priority.High, Backend

#142 Update UserGuide
  docs/UserGuide.md
Labels: UG

#141 Fix bugs in the success message of event command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/model/event/Event.java
Labels: Frontend, alpha-bug

#140 Fix bug in EventCard
  src/main/java/seedu/address/ui/EventCard.java
Labels: Frontend
